### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [VitaTretiak/Grid-Template-Project#1]
1)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/98130888-695b9e00-1ec3-11eb-8b43-1bbb6e1921ca.png)

2)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/98130943-7b3d4100-1ec3-11eb-9f23-39886ca3260b.png)

3)
требования к высоте не выполнены
![image](https://user-images.githubusercontent.com/8464662/98130670-30232e00-1ec3-11eb-995f-01e5df162e94.png)

4)
оформление не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/98130747-429d6780-1ec3-11eb-8968-7722a8de2a88.png)

**Comment by Alecto** [comment]
1 - не исправлено
3 - не исправлено

5)
здесь вообще каша
![image](https://user-images.githubusercontent.com/8464662/98251310-3a0b6680-1f81-11eb-83b4-5144ca01c17f.png)

**Comment by VitaTretiak** [comment]
Здравствуйте! Попытка номер 3
https://vitatretiak.github.io/Grid-Template-Project/?#

чт, 5 нояб. 2020 г. в 16:09, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
3 - не исправлено.
требования к высоте не выполнены
![image](https://user-images.githubusercontent.com/8464662/98434457-74d3e280-20d8-11eb-9c2e-a4ed6b84f7b5.png)

6)
размер шрифта не соответствует макету.
проверяйте для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/98434468-a9e03500-20d8-11eb-81af-17820ee056ee.png)

7)
размер шрифта не соответствует макету.
проверяйте для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/98434476-be243200-20d8-11eb-89c3-b32bb85e806d.png)

**Comment by Alecto** [comment]
ответил там же.

пт, 6 лист. 2020 о 13:32 VitaTretiak <notifications@github.com> пише:
